/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#ffffff",
      black: "#000000",
      lightgrey: "#3f3c37",
      grey: "rgba(40, 36, 30, 0.62)",
      lightpink: "#FAF7F0",
      pink: "#B08D57",
      bgpink: "rgba(176, 141, 87, 0.12)",
      darkpink: "#F3ECDD",
      lightblack: "#2A2723",
      textbl: "#2A2723",
      footerlinks: "rgba(42, 39, 35, 0.85)",
      bordertop: "rgba(105, 96, 75, 0.2)",
      darkgrey: "rgba(26, 23, 20, 0.85)",
      charcoal: "#1C1A17",
      gold: "#B08D57",
      lightgold: "#D9C398",
      cream: "#FAF7F0",
    },
    fontSize: {
      xs: ["0.75rem", { lineHeight: "1rem" }],
      sm: ["0.875rem", { lineHeight: "1.25rem" }],
      base: ["1rem", { lineHeight: "1.5rem" }],
      lg: ["1.125rem", { lineHeight: "1.75rem" }],
      xl: ["1.25rem", { lineHeight: "1.75rem" }],
      "2xl": ["1.5rem", { lineHeight: "2rem" }],
      "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
      "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
      "5xl": ["3rem", { lineHeight: "4.25rem" }],
      "6xl": ["3.75rem", { lineHeight: "1" }],
      "7xl": ["4.5rem", { lineHeight: "6.75rem" }],
      "8xl": ["6rem", { lineHeight: "1" }],
      "9xl": ["8rem", { lineHeight: "1" }],
    },
    extend: {
      fontFamily: {
        serif: ["'Playfair Display'", "serif"],
        sans: ["'Jost'", "sans-serif"],
      },
    },
  },
  plugins: [],
};
